# creates union of all stations, from all tables
# the sql query generated by minmax_lat_lng.sh -> select_stations()
# run: $ cat crt_station_view.sql | sqlite3 bikeshares.sqlite
CREATE VIEW v_stations (id, name, lng, lat) AS
SELECT start_station_id AS id, start_station_name AS name, start_lng AS lng, start_lat AS lat FROM b_202106 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202106 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202107 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202107 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202108 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202108 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202109 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202109 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202110 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202110 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202111 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202111 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202112 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202112 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202201 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202201 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202202 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202202 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202203 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202203 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202204 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202204 UNION
SELECT start_station_id, start_station_name, start_lng, start_lat FROM b_202205 UNION SELECT end_station_id, end_station_name, end_lng, end_lat FROM b_202205;
